"""change version type

Revision ID: 3e2214cf684e
Revises: 6a2d3b250521
Create Date: 2025-09-03 21:06:47.783073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2214cf684e'
down_revision: Union[str, Sequence[str], None] = '6a2d3b250521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'version',
               existing_type=sa.INTEGER(),
               server_default='1.0.0',
               type_=sa.String(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'version',
               existing_type=sa.String(length=16),
               server_default=None,
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
