"""restaurant versions

Revision ID: c034963b3118
Revises: 9d5e4ae3084a
Create Date: 2025-09-05 19:51:38.824688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c034963b3118'
down_revision: Union[str, Sequence[str], None] = '9d5e4ae3084a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('version', sa.String(length=16), server_default='0.0.1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'version')
    # ### end Alembic commands ###
